// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8rJWiJ9DqR9DhcQJTMCB9gIQk4hrEk4',
    appId: '1:809089829884:web:9be4ed976a826e31570079',
    messagingSenderId: '809089829884',
    projectId: 'chat-app-8c008',
    authDomain: 'chat-app-8c008.firebaseapp.com',
    storageBucket: 'chat-app-8c008.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeIx0xUsz3ubC9h5tFHPEIFpzi_UY1Ho',
    appId: '1:809089829884:android:1a61c2ba7e36ff9b570079',
    messagingSenderId: '809089829884',
    projectId: 'chat-app-8c008',
    storageBucket: 'chat-app-8c008.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_n-_shppQcqdFh4zSlZAG7Z_9jtIukKM',
    appId: '1:809089829884:ios:49c00a7c2aa3db27570079',
    messagingSenderId: '809089829884',
    projectId: 'chat-app-8c008',
    storageBucket: 'chat-app-8c008.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );
}
